In [1]:
import os
import sys
import pandas as pd
pd.set_option('display.max_rows', None)

from IPython.display import Markdown, display

In [2]:
parent_dir = os.path.dirname(os.getcwd())
sys.path.append(parent_dir)

In [3]:
from src.ds import read_csv, build_feature_pipeline

c:\Users\pdoub\my-projects\ds-assistant\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
file_path = os.path.join(parent_dir, "workspace", "claim_data.csv")

df = read_csv(file_path)

In [5]:
df.head(2)

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,...,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,4,0

In [6]:
feature_pipeline = build_feature_pipeline()

In [6]:
from src.ds import summarize_dataframe

summarize_dataframe(df)

{'shape': (58592, 41),
 'row_count': 58592,
 'column_count': 41,
 'columns': ['policy_id',
  'subscription_length',
  'vehicle_age',
  'customer_age',
  'region_code',
  'region_density',
  'segment',
  'model',
  'fuel_type',
  'max_torque',
  'max_power',
  'engine_type',
  'airbags',
  'is_esc',
  'is_adjustable_steering',
  'is_tpms',
  'is_parking_sensors',
  'is_parking_camera',
  'rear_brakes_type',
  'displacement',
  'cylinder',
  'transmission_type',
  'steering_type',
  'turning_radius',
  'length',
  'width',
  'gross_weight',
  'is_front_fog_lights',
  'is_rear_window_wiper',
  'is_rear_window_washer',
  'is_rear_window_defogger',
  'is_brake_assist',
  'is_power_door_locks',
  'is_central_locking',
  'is_power_steering',
  'is_driver_seat_height_adjustable',
  'is_day_night_rear_view_mirror',
  'is_ecw',
  'is_speed_alert',
  'ncap_rating',
  'claim_status'],
 'column_type_counts': {'numeric': 13,
  'datetime': 0,
  'categorical': 28,
  'other': 0},
 'missingness': {'total_missing_cells': 0, 'missing_cell_rate': 0.0}}

In [7]:
from src.ds import summarize_dataframe_columns

summarize_dataframe_columns(df)

,column,dtype,row_count,non_null_count,missing_count,missing_rate,unique_count,mean,std,min,p25,p50,p75,max
0,policy_id,object,58592,58592,0,0.0,58592,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,subscription_length,float64,58592,58592,0,0.0,140,6.111688,4.142790,0.0,2.1,5.7,10.4,14.0
2,vehicle_age,float64,58592,58592,0,0.0,49,1.388473,1.134413,0.0,0.4,1.2,2.2,20.0
3,customer_age,int64,58592,58592,0,0.0,41,44.823935,6.935604,35.0,39.0,44.0,49.0,75.0
4,region_code,object,58592,58592,0,0.0,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,region_density,int64,58592,58592,0,0.0,22,18826.858667,17660.174792,290.0,6112.0,8794.0,27003.0,73430.0
6,segment,object,58592,58592,0,0.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,model,object,58592,58592,0,0.0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,fuel_type,object,58592,58592,0,0.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,max_torque,object,58592,58592,0,0.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,max_power,object,58592,58592,0,0.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,engine_type,object,58592,58592,0,0.0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,airbags,int64,58592,58592,0,0.0,3,3.137066,1.832641,1.0,2.0,2.0,6.0,6.0
13,is_esc,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,is_adjustable_steering,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,is_tpms,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,is_parking_sensors,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,is_parking_camera,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,rear_brakes_type,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,displacement,int64,58592,58592,0,0.0,9,1162.355851,266.304786,796.0,796.0,1197.0,1493.0,1498.0
20,cylinder,int64,58592,58592,0,0.0,2,3.626963,0.483616,3.0,3.0,4.0,4.0,4.0
21,transmission_type,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,steering_type,object,58592,58592,0,0.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,turning_radius,float64,58592,58592,0,0.0,9,4.852893,0.228061,4.5,4.6,4.8,5.0,5.2
24,length,int64,58592,58592,0,0.0,9,3850.476891,311.457119,3445.0,3445.0,3845.0,3995.0,4300.0
25,width,int64,58592,58592,0,0.0,10,1672.233667,112.089135,1475.0,1515.0,1735.0,1755.0,1811.0
26,gross_weight,int64,58592,58592,0,0.0,10,1385.276813,212.423085,1051.0,1185.0,1335.0,1510.0,1720.0
27,is_front_fog_lights,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,is_rear_window_wiper,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,is_rear_window_washer,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,is_rear_window_defogger,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,is_brake_assist,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,is_power_door_locks,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,is_central_locking,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,is_power_steering,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,is_driver_seat_height_adjustable,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,is_day_night_rear_view_mirror,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,is_ecw,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,is_speed_alert,object,58592,58592,0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,ncap_rating,int64,58592,58592,0,0.0,5,1.759950,1.389576,0.0,0.0,2.0,3.0,5.0
40,claim_status,int64,58592,58592,0,0.0,2,0.063968,0.244698,0.0,0.0,0.0,0.0,1.0

In [8]:
from src.ds import summarize_target

summarize_target(df, "claim_status")

{'target_column': 'claim_status',
 'row_count': 58592,
 'non_null_count': 58592,
 'missing_count': 0,
 'unique_count': 2,
 'base_rate': 0.06396777717094485}

In [9]:
from src.ds import FeatureScreenConfig, screen_features

screen_config = FeatureScreenConfig(
    max_missing_frac=0.98,
    near_constant_thresh=0.995,
    min_non_null=100,
    top_k_univariate=25,
)

screen_result = screen_features(df, target_column="claim_status", config=screen_config)

In [10]:
screen_result.metrics

{'candidate_feature_count': 40,
 'selected_feature_count': 25,
 'dropped_feature_count': 15}

In [11]:
screen_result.selected_columns

['subscription_length',
 'region_code',
 'vehicle_age',
 'customer_age',
 'cylinder',
 'region_density',
 'is_tpms',
 'rear_brakes_type',
 'is_adjustable_steering',
 'max_torque',
 'max_power',
 'transmission_type',
 'displacement',
 'width',
 'length',
 'segment',
 'is_parking_camera',
 'is_front_fog_lights',
 'is_brake_assist',
 'model',
 'engine_type',
 'is_rear_window_wiper',
 'is_rear_window_washer',
 'steering_type',
 'is_driver_seat_height_adjustable']

In [12]:
screen_result.dropped_columns

['policy_id',
 'fuel_type',
 'airbags',
 'is_esc',
 'is_parking_sensors',
 'turning_radius',
 'gross_weight',
 'is_rear_window_defogger',
 'is_power_door_locks',
 'is_central_locking',
 'is_power_steering',
 'is_day_night_rear_view_mirror',
 'is_ecw',
 'is_speed_alert',
 'ncap_rating']

In [13]:
from src.ds import analyze_feature_correlation

corr_pairs = analyze_feature_correlation(df, target_column="claim_status", id_columns=["policy_id"])

In [14]:
corr_pairs.dropped_columns

['length']

In [15]:
from src.ds import rank_features_by_lightgbm

rank_result = rank_features_by_lightgbm(df, target_column="claim_status", feature_columns=screen_result.selected_columns, keep_top_k=20)

In [16]:
rank_result.evaluation_summary

{'ppv_at_p': 0.1348122866894198,
 'recall_at_p': 0.10533333333333333,
 'lift_at_p': 2.1064869169510807,
 'base_rate': 0.06399863469579316,
 'top_p': 0.05}

In [18]:
from src.ds import TabularTorchPreprocessor, make_binary_dataloader, train_binary_classifier, predict_proba

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from src.ds.nn import (
    RealMLP,
    TabularTorchPreprocessor,
    make_binary_dataloader,
    predict_proba,
    train_binary_classifier,
)

target_column = "claim_status"
positive_label = 1

# Split target from features.
X = df.drop(columns=[target_column]).copy()
y_raw = df[target_column].copy()

# Encode binary target as 0/1.
if y_raw.dtype == "O" or str(y_raw.dtype).startswith(("category", "string")):
    y = (y_raw == positive_label).astype(np.float32)
else:
    y = y_raw.astype(np.float32)

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y,
)

# Fit preprocessing on train only.
preprocessor = TabularTorchPreprocessor(
    numeric_scaling="robust",
    min_category_frequency=5,
    max_categories=None,
)

train_features = preprocessor.fit_transform(X_train)
valid_features = preprocessor.transform(X_valid)

# Build model with numeric width + categorical embedding tables.
model = RealMLP(
    input_dim=train_features["x_num"].shape[1],
    category_cardinalities=preprocessor.get_category_cardinalities(),
    hidden_dim=256,
    num_blocks=4,
    output_dim=1,
)

train_loader = make_binary_dataloader(
    train_features,
    y_train,
    batch_size=256,
    shuffle=True,
)

train_binary_classifier(
    model,
    train_loader,
    epochs=40,
    lr=1e-3,
    weight_decay=1e-4,
    device="cpu",  # use "cuda" if available
)

valid_scores = predict_proba(model, valid_features)

scored_valid = X_valid.copy()
scored_valid[target_column] = y_valid.values
scored_valid["claim_status_score"] = valid_scores

scored_valid.sort_values("claim_status_score", ascending=False).head()

Epoch 01 | loss=0.2427
Epoch 02 | loss=0.2364
Epoch 03 | loss=0.2351
Epoch 04 | loss=0.2348
Epoch 05 | loss=0.2360
Epoch 06 | loss=0.2336
Epoch 07 | loss=0.2346
Epoch 08 | loss=0.2336
Epoch 09 | loss=0.2334
Epoch 10 | loss=0.2329
Epoch 11 | loss=0.2343
Epoch 12 | loss=0.2341
Epoch 13 | loss=0.2336
Epoch 14 | loss=0.2328
Epoch 15 | loss=0.2313
Epoch 16 | loss=0.2322
Epoch 17 | loss=0.2323
Epoch 18 | loss=0.2318
Epoch 19 | loss=0.2323
Epoch 20 | loss=0.2325
Epoch 21 | loss=0.2320
Epoch 22 | loss=0.2304
Epoch 23 | loss=0.2315
Epoch 24 | loss=0.2310
Epoch 25 | loss=0.2324
Epoch 26 | loss=0.2303
Epoch 27 | loss=0.2293
Epoch 28 | loss=0.2295
Epoch 29 | loss=0.2296
Epoch 30 | loss=0.2281
Epoch 31 | loss=0.2292
Epoch 32 | loss=0.2292
Epoch 33 | loss=0.2282
Epoch 34 | loss=0.2275
Epoch 35 | loss=0.2275
Epoch 36 | loss=0.2279
Epoch 37 | loss=0.2285
Epoch 38 | loss=0.2267
Epoch 39 | loss=0.2267
Epoch 40 | loss=0.2281

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status,claim_status_score
5564,POL004194,6.9,2.6,45,C17,65567,Utility,M10,CNG,85Nm@3000rpm,...,No,No,No,No,No,No,Yes,0,0.0,0.412619
5856,POL003043,7.2,2.2,47,C17,65567,Utility,M10,CNG,85Nm@3000rpm,...,No,No,No,No,No,No,Yes,0,0.0,0.410310
29883,POL037624,4.4,2.6,43,C3,4076,Utility,M10,CNG,85Nm@3000rpm,...,No,No,No,No,No,No,Yes,0,0.0,0.379326
27773,POL022190,5.9,1.6,43,C5,34738,Utility,M10,CNG,85Nm@3000rpm,...,No,No,No,No,No,No,Yes,0,0.0,0.366263
40959,POL012778,6.6,1.8,42,C15,290,Utility,M10,CNG,85Nm@3000rpm,...,No,No,No,No,No,No,Yes,0,0.0,0.365342

In [35]:
from src.ds import ppv_at_top_p

ppv_at_top_p(
    y_true=scored_valid["claim_status"],
    y_score=scored_valid["claim_status_score"],
    p=0.05,
)

0.11433447098976109

In [18]:
from src.ds import build_train_valid_frames, fit_lightgbm_binary, SplitConfig

split_config = SplitConfig(
    valid_frac=0.2,
    stratify=True,
)

split = build_train_valid_frames(
    df,
    target_column="claim_status",
    feature_columns=rank_result.selected_columns,
    split_config=split_config,
)
    
    
train_result = fit_lightgbm_binary(
    train_df=split.train_df,
    valid_df=split.valid_df,
    target_column="claim_status",
    feature_columns=rank_result.selected_columns,
    categorical_columns=screen_result.categorical_columns,
)

In [19]:
from src.ds import score_lightgbm_dataframe

df["pred"] = score_lightgbm_dataframe(
    dataframe=df,
    booster=train_result.booster,
    feature_columns=rank_result.selected_columns,
    categorical_columns=screen_result.categorical_columns,
    best_iteration=train_result.best_iteration,
)

In [20]:
from src.ds import ppv_at_top_p

ppv_at_top_p(
    y_true=df["claim_status"],
    y_score=df["pred"],
    p=0.1,
)

0.1477815699658703

In [21]:
df.head()

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status,pred
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0,0.067611
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,4,0,0.072760
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0,0.069506
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,...,No,No,Yes,No,No,No,Yes,0,0,0.057187
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,...,Yes,Yes,Yes,No,No,Yes,Yes,5,0,0.066706

In [22]:
from src.ds import build_feature_pipeline, list_pipeline_params

feature_pipeline = build_feature_pipeline()

In [23]:
list_pipeline_params(feature_pipeline)

,param,value_type,value
0,map_yes_no__columns,list,"[is_front_fog_lights, is_rear_window_wiper, is..."
1,map_yes_no__no_value,int,0
2,map_yes_no__unknown_value,int,-1
3,map_yes_no__yes_value,int,1
4,memory,NoneType,None
5,parse_specs__drop_original,bool,True
6,parse_specs__power_column,str,max_power
7,parse_specs__torque_column,str,max_torque
8,preprocess__cat__impute__add_indicator,bool,False
9,preprocess__cat__impute__copy,bool,True
10,preprocess__cat__impute__fill_value,NoneType,None
11,preprocess__cat__impute__keep_empty_features,bool,False
12,preprocess__cat__impute__missing_values,float,NaN
13,preprocess__cat__impute__strategy,str,most_frequent
14,preprocess__cat__memory,NoneType,None
15,preprocess__cat__onehot__categories,str,auto
16,preprocess__cat__onehot__drop,NoneType,None
17,preprocess__cat__onehot__dtype,type,<class 'numpy.float64'>
18,preprocess__cat__onehot__feature_name_combiner,str,concat
19,preprocess__cat__onehot__handle_unknown,str,ignore
20,preprocess__cat__onehot__max_categories,NoneType,None
21,preprocess__cat__onehot__min_frequency,NoneType,None
22,preprocess__cat__onehot__sparse_output,bool,False
23,preprocess__cat__steps,list,"[(impute, SimpleImputer(strategy='most_frequen..."
24,preprocess__cat__transform_input,NoneType,None
25,preprocess__cat__verbose,bool,False
26,preprocess__force_int_remainder_cols,bool,True
27,preprocess__n_jobs,NoneType,None
28,preprocess__num__impute__add_indicator,bool,False
29,preprocess__num__impute__copy,bool,True
30,preprocess__num__impute__fill_value,NoneType,None
31,preprocess__num__impute__keep_empty_features,bool,False
32,preprocess__num__impute__missing_values,float,NaN
33,preprocess__num__impute__strategy,str,median
34,preprocess__num__memory,NoneType,None
35,preprocess__num__scale__copy,bool,True
36,preprocess__num__scale__with_mean,bool,True
37,preprocess__num__scale__with_std,bool,True
38,preprocess__num__steps,list,"[(impute, SimpleImputer(strategy='median')), (..."
39,preprocess__num__transform_input,NoneType,None
40,preprocess__num__verbose,bool,False
41,preprocess__remainder,str,drop
42,preprocess__sparse_threshold,float,0.3
43,preprocess__transformer_weights,NoneType,None
44,preprocess__transformers,list,"[(num, (SimpleImputer(strategy='median'), Stan..."
45,preprocess__verbose,bool,False
46,preprocess__verbose_feature_names_out,bool,False
47,steps,list,"[(parse_specs, CarSpecParser()), (map_yes_no, ..."
48,transform_input,NoneType,None
49,variance__threshold,float,0.0
50,verbose,bool,False

In [27]:
x_train = feature_pipeline.fit_transform(split.train_df)

y_train = split.train_df['claim_status']

In [24]:
from src.ds import PipelineSearchSpace


search_space = [
    PipelineSearchSpace(
        estimator_param="parse_specs__drop_original",
        suggestion_kind="bool",
        default=True,
        description="Whether to drop raw max_torque and max_power string columns.",
    ),
    PipelineSearchSpace(
        estimator_param="preprocess__num__impute__strategy",
        suggestion_kind="categorical",
        default="median",
        choices=["median", "mean"],
        description="Numeric imputation strategy.",
    ),
    PipelineSearchSpace(
        estimator_param="preprocess__cat__onehot__min_frequency",
        suggestion_kind="int",
        default=10,
        low=2,
        high=100,
        log=True,
        description="Minimum category frequency before grouping rare levels.",
    ),
    PipelineSearchSpace(
        estimator_param="variance__threshold",
        suggestion_kind="float",
        default=0.0,
        low=0.0,
        high=0.01,
        step=0.001,
        description="Low-variance feature filter threshold.",
    ),
]

In [25]:
from src.ds import validate_pipeline_search_space

validate_pipeline_search_space(feature_pipeline, search_space)

In [26]:
from src.ds import tune_lightgbm_pipeline


hpo_result = tune_lightgbm_pipeline(
    dataframe=df,
    target_column="claim_status",
    pipeline=feature_pipeline,
    pipeline_search_space=search_space,
    feature_columns=rank_result.selected_columns,
)

[I 2026-04-23 21:09:01,565] A new study created in memory with name: no-name-0c51f2f6-21f4-4990-964b-6b005d32b943

[I 2026-04-23 21:09:02,848] Trial 0 finished with value: 0.13651877133105803 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 3, 'variance__threshold': 0.001, 'lgbm__boosting_type': 'goss', 'lgbm__max_depth': 6, 'lgbm__learning_rate': 0.048952790869270256, 'lgbm__num_leaves': 67, 'lgbm__min_child_samples': 181, 'lgbm__min_child_weight': 0.0028585493941961923, 'lgbm__feature_fraction': 0.7365190920973087, 'lgbm__feature_fraction_bynode': 0.4836963163912251, 'lgbm__lambda_l1': 0.0028888383623653178, 'lgbm__lambda_l2': 0.006789053271698486, 'lgbm__min_gain_to_split': 0.9121399684340719, 'lgbm__extra_trees': False, 'lgbm__linear_tree': True, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 17.052412368729154, 'lgbm__cat_l2': 6.505159298527952, 'lgbm__max_cat_to_onehot': 61, 'lgbm__min_data_per_group': 437, 'lgbm__max_cat_threshold': 130, 'lgbm__top_rate': 0.2218455076693483, 'lgbm__other_rate': 0.08418523990223437, 'lgbm__class_weight_mode': 'none'}. Best is trial 0 with value: 0.13651877133105803.
[I 2026-04-23 21:09:03,972] Trial 1 finished with value: 0.1348122866894198 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'mean', 'preprocess__cat__onehot__min_frequency': 4, 'variance__threshold': 0.007, 'lgbm__boosting_type': 'goss', 'lgbm__max_depth': 5, 'lgbm__learning_rate': 0.0345919352429327, 'lgbm__num_leaves': 27, 'lgbm__min_child_samples': 57, 'lgbm__min_child_weight': 0.004233032996527599, 'lgbm__feature_fraction': 0.6137725093292151, 'lgbm__feature_fraction_bynode': 0.5628094190643376, 'lgbm__lambda_l1': 1.3921548533046495, 'lgbm__lambda_l2': 0.0060780830996819525, 'lgbm__min_gain_to_split': 0.5618690193747615, 'lgbm__extra_trees': False, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': False, 'lgbm__cat_smooth': 19.87156815341724, 'lgbm__cat_l2': 0.5522117123602399, 'lgbm__max_cat_to_onehot': 53, 'lgbm__min_data_per_group': 157, 'lgbm__max_cat_threshold': 98, 'lgbm__top_rate': 0.4085081386743783, 'lgbm__other_rate': 0.07591562810693163, 'lgbm__class_weight_mode': 'none'}. Best is trial 0 with value: 0.13651877133105803.
[I 2026-04-23 21:09:05,439] Trial 2 finished with value: 0.12286689419795221 and parameters: {'parse_specs__drop_original': False, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 6, 'variance__threshold': 0.003, 'lgbm__boosting_type': 'gbdt', 'lgbm__max_depth': -1, 'lgbm__learning_rate': 0.06958182619418249, 'lgbm__num_leaves': 51, 'lgbm__min_child_samples': 53, 'lgbm__min_child_weight': 0.00034630370261191863, 'lgbm__feature_fraction': 0.41728605212770387, 'lgbm__feature_fraction_bynode': 0.7818462467582683, 'lgbm__lambda_l1': 0.003730610475453594, 'lgbm__lambda_l2': 0.03490225247838249, 'lgbm__min_gain_to_split': 1.815132947852186, 'lgbm__extra_trees': True, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 16.122128725400444, 'lgbm__cat_l2': 92.96976523425731, 'lgbm__max_cat_to_onehot': 52, 'lgbm__min_data_per_group': 117, 'lgbm__max_cat_threshold': 163, 'lgbm__bagging_fraction': 0.8616524346046015, 'lgbm__bagging_freq': 2, 'lgbm__class_weight_mode': 'none'}. Best is trial 0 with value: 0.13651877133105803.
[I 2026-04-23 21:09:06,532] Trial 3 finished with value: 0.14505119453924914 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 4, 'variance__threshold': 0.004, 'lgbm__boosting_type': 'goss', 'lgbm__max_depth': 10, 'lgbm__learning_rate': 0.06914174528278788, 'lgbm__num_leaves': 111, 'lgbm__min_child_samples': 148, 'lgbm__min_child_weight': 7.226207258080486, 'lgbm__feature_fraction': 0.9293460122181612, 'lgbm__feature_fraction_bynode': 0.5510693774952184, 'lgbm__lambda_l1': 0.030636738485558444, 'lgbm__lambda_l2': 0.0031944165636003663, 'lgbm__min_gain_to_split': 0.5696809887549352, 'lgbm__extra_trees': True, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 23.95618906669724, 'lgbm__cat_l2': 14.48948720912231, 'lgbm__max_cat_to_onehot': 32, 'lgbm__min_data_per_group': 473, 'lgbm__max_cat_threshold': 18, 'lgbm__top_rate': 0.3688542189623515, 'lgbm__other_rate': 0.3165668653650512, 'lgbm__class_weight_mode': 'scale_pos_weight', 'lgbm__scale_pos_weight': 12.18380711609311}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:07,730] Trial 4 finished with value: 0.14334470989761092 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 50, 'variance__threshold': 0.003, 'lgbm__boosting_type': 'gbdt', 'lgbm__max_depth': 12, 'lgbm__learning_rate': 0.0559033278213289, 'lgbm__num_leaves': 214, 'lgbm__min_child_samples': 75, 'lgbm__min_child_weight': 0.005073781437488639, 'lgbm__feature_fraction': 0.462410436682324, 'lgbm__feature_fraction_bynode': 0.9548161709671377, 'lgbm__lambda_l1': 2.436109284179989, 'lgbm__lambda_l2': 0.0019485346746590901, 'lgbm__min_gain_to_split': 1.319968092068358, 'lgbm__extra_trees': False, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 90.04180571633304, 'lgbm__cat_l2': 63.31014572732679, 'lgbm__max_cat_to_onehot': 22, 'lgbm__min_data_per_group': 38, 'lgbm__max_cat_threshold': 97, 'lgbm__bagging_fraction': 0.9036996169786596, 'lgbm__bagging_freq': 7, 'lgbm__class_weight_mode': 'none'}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:08,857] Trial 5 finished with value: 0.11945392491467577 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 2, 'variance__threshold': 0.001, 'lgbm__boosting_type': 'gbdt', 'lgbm__max_depth': 8, 'lgbm__learning_rate': 0.09974619905830319, 'lgbm__num_leaves': 96, 'lgbm__min_child_samples': 636, 'lgbm__min_child_weight': 0.19411739809629622, 'lgbm__feature_fraction': 0.7125697318345094, 'lgbm__feature_fraction_bynode': 0.4562048606968555, 'lgbm__lambda_l1': 0.006895710419314547, 'lgbm__lambda_l2': 0.00211841888032146, 'lgbm__min_gain_to_split': 0.48797928675816715, 'lgbm__extra_trees': False, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': False, 'lgbm__cat_smooth': 57.69038846263591, 'lgbm__cat_l2': 49.25176938188639, 'lgbm__max_cat_to_onehot': 13, 'lgbm__min_data_per_group': 167, 'lgbm__max_cat_threshold': 20, 'lgbm__bagging_fraction': 0.5109421848941542, 'lgbm__bagging_freq': 5, 'lgbm__class_weight_mode': 'scale_pos_weight', 'lgbm__scale_pos_weight': 27.45855861892459}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:09,951] Trial 6 finished with value: 0.11945392491467577 and parameters: {'parse_specs__drop_original': False, 'preprocess__num__impute__strategy': 'mean', 'preprocess__cat__onehot__min_frequency': 9, 'variance__threshold': 0.01, 'lgbm__boosting_type': 'gbdt', 'lgbm__max_depth': 10, 'lgbm__learning_rate': 0.0750891024620078, 'lgbm__num_leaves': 20, 'lgbm__min_child_samples': 314, 'lgbm__min_child_weight': 8.9180366028978, 'lgbm__feature_fraction': 0.4770462083800882, 'lgbm__feature_fraction_bynode': 0.710997791418242, 'lgbm__lambda_l1': 2.4370551632385427, 'lgbm__lambda_l2': 0.5056419398267449, 'lgbm__min_gain_to_split': 1.394031481990536, 'lgbm__extra_trees': False, 'lgbm__linear_tree': True, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 91.32405525564712, 'lgbm__cat_l2': 51.13423988609378, 'lgbm__max_cat_to_onehot': 33, 'lgbm__min_data_per_group': 225, 'lgbm__max_cat_threshold': 74, 'lgbm__bagging_fraction': 0.8158850947659665, 'lgbm__bagging_freq': 6, 'lgbm__class_weight_mode': 'none'}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:11,532] Trial 7 finished with value: 0.12627986348122866 and parameters: {'parse_specs__drop_original': False, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 11, 'variance__threshold': 0.005, 'lgbm__boosting_type': 'goss', 'lgbm__max_depth': 5, 'lgbm__learning_rate': 0.08175287102555757, 'lgbm__num_leaves': 20, 'lgbm__min_child_samples': 58, 'lgbm__min_child_weight': 0.04537045742450091, 'lgbm__feature_fraction': 0.6973493168855586, 'lgbm__feature_fraction_bynode': 0.782457940898924, 'lgbm__lambda_l1': 0.42702831090490767, 'lgbm__lambda_l2': 7.572868182332343, 'lgbm__min_gain_to_split': 1.0326006966023906, 'lgbm__extra_trees': True, 'lgbm__linear_tree': True, 'lgbm__force_row_wise': False, 'lgbm__cat_smooth': 96.26484146779251, 'lgbm__cat_l2': 83.59801205122058, 'lgbm__max_cat_to_onehot': 45, 'lgbm__min_data_per_group': 48, 'lgbm__max_cat_threshold': 14, 'lgbm__top_rate': 0.1625748170684344, 'lgbm__other_rate': 0.1375850143576084, 'lgbm__class_weight_mode': 'scale_pos_weight', 'lgbm__scale_pos_weight': 18.27401311231577}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:12,712] Trial 8 finished with value: 0.12286689419795221 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 20, 'variance__threshold': 0.004, 'lgbm__boosting_type': 'goss', 'lgbm__max_depth': 8, 'lgbm__learning_rate': 0.035115948094414484, 'lgbm__num_leaves': 61, 'lgbm__min_child_samples': 205, 'lgbm__min_child_weight': 0.0007345296810407679, 'lgbm__feature_fraction': 0.6386184070808851, 'lgbm__feature_fraction_bynode': 0.639102840638424, 'lgbm__lambda_l1': 0.12001913440860316, 'lgbm__lambda_l2': 0.1497849760587998, 'lgbm__min_gain_to_split': 0.09060801954408904, 'lgbm__extra_trees': True, 'lgbm__linear_tree': True, 'lgbm__force_row_wise': False, 'lgbm__cat_smooth': 7.056874740042984, 'lgbm__cat_l2': 64.24192782063156, 'lgbm__max_cat_to_onehot': 2, 'lgbm__min_data_per_group': 97, 'lgbm__max_cat_threshold': 208, 'lgbm__top_rate': 0.3301896711503516, 'lgbm__other_rate': 0.18585947417228266, 'lgbm__class_weight_mode': 'none'}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:13,921] Trial 9 finished with value: 0.12286689419795221 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'mean', 'preprocess__cat__onehot__min_frequency': 68, 'variance__threshold': 0.002, 'lgbm__boosting_type': 'goss', 'lgbm__max_depth': 8, 'lgbm__learning_rate': 0.0472203593609457, 'lgbm__num_leaves': 22, 'lgbm__min_child_samples': 402, 'lgbm__min_child_weight': 0.13954498518315703, 'lgbm__feature_fraction': 0.882609607439879, 'lgbm__feature_fraction_bynode': 0.8410426262823314, 'lgbm__lambda_l1': 1.0408895582954845, 'lgbm__lambda_l2': 0.0025714190847345355, 'lgbm__min_gain_to_split': 0.35487908755944564, 'lgbm__extra_trees': True, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 34.08035402530179, 'lgbm__cat_l2': 93.07573256035647, 'lgbm__max_cat_to_onehot': 55, 'lgbm__min_data_per_group': 52, 'lgbm__max_cat_threshold': 106, 'lgbm__top_rate': 0.40181714963387294, 'lgbm__other_rate': 0.08609335409257642, 'lgbm__class_weight_mode': 'none'}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:15,703] Trial 10 finished with value: 0.12627986348122866 and parameters: {'parse_specs__drop_original': False, 'preprocess__num__impute__strategy': 'mean', 'preprocess__cat__onehot__min_frequency': 27, 'variance__threshold': 0.007, 'lgbm__boosting_type': 'goss', 'lgbm__max_depth': 10, 'lgbm__learning_rate': 0.14059575788857293, 'lgbm__num_leaves': 202, 'lgbm__min_child_samples': 116, 'lgbm__min_child_weight': 9.158267559026646, 'lgbm__feature_fraction': 0.9458220291949924, 'lgbm__feature_fraction_bynode': 0.407296324965305, 'lgbm__lambda_l1': 0.00023368763747518765, 'lgbm__lambda_l2': 0.0002481861060520505, 'lgbm__min_gain_to_split': 0.854793330144897, 'lgbm__extra_trees': True, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 58.677843130539436, 'lgbm__cat_l2': 24.776635635842464, 'lgbm__max_cat_to_onehot': 36, 'lgbm__min_data_per_group': 11, 'lgbm__max_cat_threshold': 32, 'lgbm__top_rate': 0.29254597569975715, 'lgbm__other_rate': 0.3525872257593396, 'lgbm__class_weight_mode': 'scale_pos_weight', 'lgbm__scale_pos_weight': 7.763032367476102}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:16,966] Trial 11 finished with value: 0.12798634812286688 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 81, 'variance__threshold': 0.006, 'lgbm__boosting_type': 'gbdt', 'lgbm__max_depth': 12, 'lgbm__learning_rate': 0.05177045390637458, 'lgbm__num_leaves': 253, 'lgbm__min_child_samples': 123, 'lgbm__min_child_weight': 0.7582687423988235, 'lgbm__feature_fraction': 0.5358382942535596, 'lgbm__feature_fraction_bynode': 0.9944831673649545, 'lgbm__lambda_l1': 9.551793982137914, 'lgbm__lambda_l2': 0.00022403510192052088, 'lgbm__min_gain_to_split': 1.3939440648124213, 'lgbm__extra_trees': False, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 75.82236170130739, 'lgbm__cat_l2': 32.88139524964877, 'lgbm__max_cat_to_onehot': 20, 'lgbm__min_data_per_group': 16, 'lgbm__max_cat_threshold': 42, 'lgbm__bagging_fraction': 0.9422087705500121, 'lgbm__bagging_freq': 7, 'lgbm__class_weight_mode': 'scale_pos_weight', 'lgbm__scale_pos_weight': 10.034222581675749}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:18,200] Trial 12 finished with value: 0.12116040955631399 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 39, 'variance__threshold': 0.0, 'lgbm__boosting_type': 'gbdt', 'lgbm__max_depth': 4, 'lgbm__learning_rate': 0.05658179868517563, 'lgbm__num_leaves': 141, 'lgbm__min_child_samples': 108, 'lgbm__min_child_weight': 0.0061035924261092795, 'lgbm__feature_fraction': 0.858506812179594, 'lgbm__feature_fraction_bynode': 0.9739133622448141, 'lgbm__lambda_l1': 0.03273659822868416, 'lgbm__lambda_l2': 0.0006860087526479414, 'lgbm__min_gain_to_split': 1.3353894207636487, 'lgbm__extra_trees': True, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 39.25086044605017, 'lgbm__cat_l2': 66.77924495840927, 'lgbm__max_cat_to_onehot': 22, 'lgbm__min_data_per_group': 26, 'lgbm__max_cat_threshold': 8, 'lgbm__bagging_fraction': 0.6570967852981849, 'lgbm__bagging_freq': 3, 'lgbm__class_weight_mode': 'scale_pos_weight', 'lgbm__scale_pos_weight': 12.988350292326448}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:19,986] Trial 13 finished with value: 0.1296928327645051 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 18, 'variance__threshold': 0.004, 'lgbm__boosting_type': 'gbdt', 'lgbm__max_depth': 12, 'lgbm__learning_rate': 0.0931540166191683, 'lgbm__num_leaves': 138, 'lgbm__min_child_samples': 87, 'lgbm__min_child_weight': 1.232140196532068, 'lgbm__feature_fraction': 0.830227855270516, 'lgbm__feature_fraction_bynode': 0.596369092127246, 'lgbm__lambda_l1': 0.0666272690638427, 'lgbm__lambda_l2': 0.029647557003430365, 'lgbm__min_gain_to_split': 1.8070178037816187, 'lgbm__extra_trees': False, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 73.2833751661706, 'lgbm__cat_l2': 23.183503872236436, 'lgbm__max_cat_to_onehot': 26, 'lgbm__min_data_per_group': 447, 'lgbm__max_cat_threshold': 62, 'lgbm__bagging_fraction': 0.6845917458605508, 'lgbm__bagging_freq': 4, 'lgbm__class_weight_mode': 'scale_pos_weight', 'lgbm__scale_pos_weight': 15.966636277927982}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:21,053] Trial 14 finished with value: 0.13310580204778158 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 6, 'variance__threshold': 0.009000000000000001, 'lgbm__boosting_type': 'goss', 'lgbm__max_depth': 7, 'lgbm__learning_rate': 0.12415622273725446, 'lgbm__num_leaves': 140, 'lgbm__min_child_samples': 152, 'lgbm__min_child_weight': 0.023029755053351447, 'lgbm__feature_fraction': 0.5574684563981175, 'lgbm__feature_fraction_bynode': 0.889671829927555, 'lgbm__lambda_l1': 0.00012346986987803223, 'lgbm__lambda_l2': 0.021328042610569316, 'lgbm__min_gain_to_split': 1.1215558173616407, 'lgbm__extra_trees': True, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 38.199961179064886, 'lgbm__cat_l2': 41.398620840270176, 'lgbm__max_cat_to_onehot': 41, 'lgbm__min_data_per_group': 32, 'lgbm__max_cat_threshold': 24, 'lgbm__top_rate': 0.47973126509494035, 'lgbm__other_rate': 0.31955531146430816, 'lgbm__class_weight_mode': 'none'}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:22,393] Trial 15 finished with value: 0.14334470989761092 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 48, 'variance__threshold': 0.003, 'lgbm__boosting_type': 'gbdt', 'lgbm__max_depth': 10, 'lgbm__learning_rate': 0.061538338765052256, 'lgbm__num_leaves': 95, 'lgbm__min_child_samples': 84, 'lgbm__min_child_weight': 0.00010618277613875839, 'lgbm__feature_fraction': 0.7826552463258808, 'lgbm__feature_fraction_bynode': 0.5330028562712287, 'lgbm__lambda_l1': 0.19432683975299878, 'lgbm__lambda_l2': 0.00010983829349374222, 'lgbm__min_gain_to_split': 0.6054472257937599, 'lgbm__extra_trees': False, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 81.83725040444273, 'lgbm__cat_l2': 70.00928614692674, 'lgbm__max_cat_to_onehot': 11, 'lgbm__min_data_per_group': 64, 'lgbm__max_cat_threshold': 11, 'lgbm__bagging_fraction': 0.8137003722507435, 'lgbm__bagging_freq': 7, 'lgbm__class_weight_mode': 'scale_pos_weight', 'lgbm__scale_pos_weight': 11.383962579323004}. Best is trial 3 with value: 0.14505119453924914.
[I 2026-04-23 21:09:23,491] Trial 16 finished with value: 0.12116040955631399 and parameters: {'parse_specs__drop_original': True, 'preprocess__num__impute__strategy': 'median', 'preprocess__cat__onehot__min_frequency': 2, 'variance__threshold': 0.005, 'lgbm__boosting_type': 'gbdt', 'lgbm__max_depth': 12, 'lgbm__learning_rate': 0.03992071091950655, 'lgbm__num_leaves': 191, 'lgbm__min_child_samples': 275, 'lgbm__min_child_weight': 0.023392803549780104, 'lgbm__feature_fraction': 0.40358009984452303, 'lgbm__feature_fraction_bynode': 0.6661613579480568, 'lgbm__lambda_l1': 0.0008674434739136055, 'lgbm__lambda_l2': 0.0007809693145018778, 'lgbm__min_gain_to_split': 0.21771477594531707, 'lgbm__extra_trees': True, 'lgbm__linear_tree': False, 'lgbm__force_row_wise': True, 'lgbm__cat_smooth': 1.6247707641024363, 'lgbm__cat_l2': 12.790078620638342, 'lgbm__max_cat_to_onehot': 28, 'lgbm__min_data_per_group': 33, 'lgbm__max_cat_threshold': 49, 'lgbm__bagging_fraction': 0.9138179501103103, 'lgbm__bagging_freq': 1, 'lgbm__class_weight_mode': 'none'}. Best is trial 3 with value: 0.14505119453924914.

In [29]:
hpo_result.best_result.evaluation_summary

{'ppv_at_p': 0.14505119453924914,
 'recall_at_p': 0.11333333333333333,
 'lift_at_p': 2.2664732650739476,
 'base_rate': 0.06399863469579316,
 'top_p': 0.05}

In [30]:
hpo_result.best_params

{'parse_specs__drop_original': True,
 'preprocess__num__impute__strategy': 'median',
 'preprocess__cat__onehot__min_frequency': 4,
 'variance__threshold': 0.004,
 'lgbm__boosting_type': 'goss',
 'lgbm__max_depth': 10,
 'lgbm__learning_rate': 0.06914174528278788,
 'lgbm__num_leaves': 111,
 'lgbm__min_child_samples': 148,
 'lgbm__min_child_weight': 7.226207258080486,
 'lgbm__feature_fraction': 0.9293460122181612,
 'lgbm__feature_fraction_bynode': 0.5510693774952184,
 'lgbm__lambda_l1': 0.030636738485558444,
 'lgbm__lambda_l2': 0.0031944165636003663,
 'lgbm__min_gain_to_split': 0.5696809887549352,
 'lgbm__extra_trees': True,
 'lgbm__linear_tree': False,
 'lgbm__force_row_wise': True,
 'lgbm__cat_smooth': 23.95618906669724,
 'lgbm__cat_l2': 14.48948720912231,
 'lgbm__max_cat_to_onehot': 32,
 'lgbm__min_data_per_group': 473,
 'lgbm__max_cat_threshold': 18,
 'lgbm__top_rate': 0.3688542189623515,
 'lgbm__other_rate': 0.3165668653650512,
 'lgbm__class_weight_mode': 'scale_pos_weight',
 'lgbm__scale_pos_weight': 12.18380711609311}